# Render.com deployment configuration
services:
  - type: web
    name: legal-ai-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    branch: main
    rootDir: backend
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ALLOWED_ORIGINS
        value: https://harshad2321.github.io
      - key: LOG_LEVEL
        value: info